# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: ruby_gpg 0.3.1 ruby lib

Gem::Specification.new do |s|
  s.name = "ruby_gpg"
  s.version = "0.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Justin Blake"]
  s.date = "2015-02-27"
  s.description = "Ruby wrapper for the gpg binary"
  s.email = "justin@megablaix.com"
  s.extra_rdoc_files = [
    "CHANGELOG.markdown",
    "LICENSE",
    "README.markdown"
  ]
  s.files = [
    ".autotest",
    ".travis.yml",
    "CHANGELOG.markdown",
    "Gemfile",
    "LICENSE",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "cucumber.yml",
    "features/decrypt_string.feature",
    "features/decryption.feature",
    "features/encryption.feature",
    "features/step_definitions/ruby_gpg_steps.rb",
    "features/support/env.rb",
    "lib/ruby_gpg.rb",
    "ruby_gpg.gemspec",
    "spec/ruby_gpg_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "test_keys/pubring.gpg",
    "test_keys/secring.gpg",
    "test_keys/trustdb.gpg"
  ]
  s.homepage = "http://github.com/blaix/ruby_gpg"
  s.rubygems_version = "2.4.6"
  s.summary = "Ruby wrapper for the gpg binary"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ruby_gpg>, [">= 0"])
      s.add_development_dependency(%q<rake>, ["~> 10.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.99.0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_development_dependency(%q<mocha>, [">= 1.1.0"])
      s.add_development_dependency(%q<jeweler>, [">= 2.0.0"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_development_dependency(%q<mocha>, [">= 0.9.8"])
    else
      s.add_dependency(%q<ruby_gpg>, [">= 0"])
      s.add_dependency(%q<rake>, ["~> 10.0"])
      s.add_dependency(%q<rspec>, ["~> 2.99.0"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<mocha>, [">= 1.1.0"])
      s.add_dependency(%q<jeweler>, [">= 2.0.0"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<mocha>, [">= 0.9.8"])
    end
  else
    s.add_dependency(%q<ruby_gpg>, [">= 0"])
    s.add_dependency(%q<rake>, ["~> 10.0"])
    s.add_dependency(%q<rspec>, ["~> 2.99.0"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<mocha>, [">= 1.1.0"])
    s.add_dependency(%q<jeweler>, [">= 2.0.0"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<mocha>, [">= 0.9.8"])
  end
end

